// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkzpgtzfsofhxbogtcdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrenBndHpmc29maHhib2d0Y2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwMjU4ODEsImV4cCI6MjA4MzYwMTg4MX0.T83hO0BRsUDR5MVYbNFd4KmEGGsYmsKd9oCZIGGztkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});